// <auto-generated />
namespace Lake_of_the_Humber.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appointmentandinvoicemodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appointmentandinvoicemodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202104041710247_appointment-and-invoice-models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
