// <auto-generated />
namespace Lake_of_the_Humber.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FAQChanges1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FAQChanges1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104091955446_FAQ Changes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
