// <auto-generated />
namespace Lake_of_the_Humber.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class attempttomaketheviewmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attempttomaketheviewmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202104102323568_attempt to make the viewmodels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
